name = "coleta-defensoria"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "assistidos-db-v2"
database_id = "9f4c9a94-e4be-4d94-80c5-46c029e902bf"
